# Generated by Django 6.0.3 on 2026-04-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='カテゴリ')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
            ],
        ),
    ]
