# Generated by Django 6.0.3 on 2026-04-15 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='カテゴリ名')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='在庫数')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='商品画像')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.category', verbose_name='カテゴリ')),
            ],
        ),
    ]
