# Generated by Django 6.0.3 on 2026-04-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_stockhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='仕入れ単価'),
        ),
    ]
