# Generated by Django 5.1.3 on 2026-04-15 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_manufacturer_product_manufacturer"),
        ("accounts", "0003_alter_category_id"),
    ]

    operations = []
