# Generated by Django 5.1.3 on 2026-04-16 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_stockhistory"),
        ("accounts", "0004_merge_20260415_1307"),
    ]

    operations = []
