# Generated by Django 5.1.3 on 2026-04-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_merge_0003_stockhistory_0004_merge_20260415_1307"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cost",
            field=models.IntegerField(default=0, verbose_name="仕入れ単価"),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="stockhistory",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
