# Generated by Django 6.0.3 on 2026-04-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='表示順'),
        ),
    ]
