# Generated by Django 5.1.3 on 2026-04-18 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_product_cost"),
        ("accounts", "0006_product_cost_alter_manufacturer_id_and_more"),
    ]

    operations = []
