# Generated by Django 5.1.3 on 2026-04-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_merge_20260418_1027"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_visible",
            field=models.BooleanField(default=True, verbose_name="商品一覧に表示"),
        ),
    ]
