# Generated by Django 6.0.3 on 2026-05-06 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_order_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=10, verbose_name='郵便番号')),
                ('prefecture', models.CharField(max_length=50, verbose_name='都道府県')),
                ('city', models.CharField(max_length=100, verbose_name='市区町村')),
                ('address', models.CharField(max_length=200, verbose_name='番地')),
                ('building', models.CharField(blank=True, max_length=200, verbose_name='建物名')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
