# Generated by Django 6.0.3 on 2026-05-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='番地'),
        ),
        migrations.AddField(
            model_name='order',
            name='building',
            field=models.CharField(blank=True, max_length=200, verbose_name='建物名'),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='市区町村'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='credit_card', max_length=50, verbose_name='支払い方法'),
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='郵便番号'),
        ),
        migrations.AddField(
            model_name='order',
            name='prefecture',
            field=models.CharField(blank=True, max_length=50, verbose_name='都道府県'),
        ),
    ]
