# Generated by Django 5.1.3 on 2026-04-29 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_product_created_at"),
        ("accounts", "0009_productimage"),
    ]

    operations = []
