# Generated by Django 5.1.3 on 2026-04-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_merge_0006_product_created_at_0009_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
