# Generated by Django 5.1.3 on 2026-04-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_productimage_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="display_order",
            field=models.PositiveIntegerField(default=0, verbose_name="表示順"),
        ),
    ]
