# Generated by Django 5.1.3 on 2026-04-29 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_order_orderitem"),
        ("accounts", "0012_product_display_order"),
    ]

    operations = []
