# Generated by Django 5.1.3 on 2026-05-06 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_order_address_order_building_order_city_and_more"),
        ("accounts", "0013_merge_0008_order_orderitem_0012_product_display_order"),
    ]

    operations = []
