# Generated by Django 5.1.3 on 2026-05-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_alter_address_id_alter_order_id_alter_orderitem_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_date",
            field=models.DateField(blank=True, null=True, verbose_name="配送希望日"),
        ),
    ]
