# Generated by Django 5.1.3 on 2026-05-06 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_order_delivery_date_order_delivery_time"),
        ("accounts", "0016_order_delivery_date"),
    ]

    operations = []
