# Generated by Django 6.0.3 on 2026-05-07 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_address_created_at_address_is_main_and_more'),
        ('accounts', '0017_merge_20260506_1239'),
    ]

    operations = [
    ]
