# Generated by Django 6.0.3 on 2026-05-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_address_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='氏名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(default='', max_length=20, verbose_name='電話番号'),
            preserve_default=False,
        ),
    ]
