# Generated by Django 6.0.3 on 2026-05-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_address_name_address_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='building',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='prefecture',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='配送先番地'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_building',
            field=models.CharField(blank=True, max_length=200, verbose_name='配送先建物名'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='配送先市区町村'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='配送先氏名'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='配送先電話番号'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='配送先郵便番号'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_prefecture',
            field=models.CharField(blank=True, max_length=50, verbose_name='配送先都道府県'),
        ),
    ]
