# Generated by Django 6.0.3 on 2026-05-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_order_address_remove_order_building_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
