# Generated by Django 6.0.3 on 2026-05-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_order_delivery_address_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '受付中'), ('preparing', '発送準備中'), ('shipped', '発送済み'), ('cancelled', 'キャンセル')], default='pending', max_length=20),
        ),
    ]
