# Generated by Django 6.0.3 on 2026-05-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '受付中'), ('payment_waiting', '入金待ち'), ('preparing', '発送準備中'), ('shipped', '発送済み'), ('cancelled', 'キャンセル')], default='pending', max_length=20),
        ),
    ]
